### ISSUE TITLE
Pick Drupal 7 and Drupal 8 theme

### ISSUE THREAD

**Issue by asghaier** [gnulugtn/portal#2]
### Suggested Drupal 7 Themes
- https://www.drupal.org/project/bootstrap_business
- https://www.drupal.org/project/pari
### Suggested Drupal 8 Themes
- https://www.drupal.org/project/integrity
- https://www.drupal.org/project/jethro
- https://www.drupal.org/project/paxton
- https://www.drupal.org/project/nero
- https://www.drupal.org/project/zircon

Scoring criteria:
- Theme regions positions
- Theme default design (colors, typography, tables lists and html elements...)
- Theme technology (SCSS, SASS, Grid System, Responsivness...)

**Comment by marwendoukh** [comment]
I suggest the Pari theme .take a look : 
http://demo.drupar.com/pari/

**Comment by asghaier** [comment]
Thank you @marwendoukh See if you can find other good drupal 7 themes and try to play with the Drupal 8 themes and scoring them.
(there is a good chance we are going to go with Drupal 8, see Drupal 8 feature discovery ticket https://github.com/gnulugtn/portal/issues/5 )

**Comment by asghaier** [comment]
@Na3iL @marwendoukh an easy way to have a quick look on themes design:
https://dropthemes.in/gallery?compatibility[]=drupal_8&sort_by=newest
We will have to test the themes on Drupal anyway. Sometimes it's not easy to make it look like the demo but that's a great quick preview.
1. select the theme
2. click preview icon on top of _add to cart_ button
3. enlarge it to open in a new tab with the demo site only

**Comment by asghaier** [comment]
We are moving back to Drupal 7 and we need to decide on a final theme @marwendoukh @Na3iL Please help decide on this asap
